
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 贵客猜菜提示语
/// </summary>
public partial class TbVipGuestDemandHint
{
    private readonly System.Collections.Generic.Dictionary<int, VipGuestDemandHint> _dataMap;
    private readonly System.Collections.Generic.List<VipGuestDemandHint> _dataList;
    
    public TbVipGuestDemandHint(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, VipGuestDemandHint>(count);
        _dataList = new System.Collections.Generic.List<VipGuestDemandHint>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            VipGuestDemandHint _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.VipGuestDemandHint.DeserializeVipGuestDemandHint(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, VipGuestDemandHint> DataMap => _dataMap;
    public System.Collections.Generic.List<VipGuestDemandHint> DataList => _dataList;

    public VipGuestDemandHint GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public VipGuestDemandHint Get(int key) => _dataMap[key];
    public VipGuestDemandHint this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

