
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 贵客猜菜提示语
/// </summary>
public sealed partial class VipGuestDemandHint : Luban.BeanBase
{
    public VipGuestDemandHint(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["text"].IsString) { throw new SerializationException(); }  Text = _buf["text"]; }
    }

    public static VipGuestDemandHint DeserializeVipGuestDemandHint(JSONNode _buf)
    {
        return new VipGuestDemandHint(_buf);
    }

    /// <summary>
    /// 模板Id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 提示语模板
    /// </summary>
    public readonly string Text;
   
    public const int __ID__ = 1691191725;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "text:" + Text + ","
        + "}";
    }
}
}

