
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 经营成就任务
/// </summary>
public sealed partial class Achievement : Luban.BeanBase
{
    public Achievement(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["achievementType"].IsNumber) { throw new SerializationException(); }  AchievementType = (AchievementType)_buf["achievementType"].AsInt; }
        { var __json0 = _buf["param"]; if(!__json0.IsArray) { throw new SerializationException(); } Param = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Param.Add(__v0); }   }
        { if(!_buf["rewardCoin"].IsNumber) { throw new SerializationException(); }  RewardCoin = _buf["rewardCoin"]; }
        { if(!_buf["reputationReward"].IsNumber) { throw new SerializationException(); }  ReputationReward = _buf["reputationReward"]; }
        { if(!_buf["icon"].IsString) { throw new SerializationException(); }  Icon = _buf["icon"]; }
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
        { if(!_buf["frame"].IsString) { throw new SerializationException(); }  Frame = _buf["frame"]; }
    }

    public static Achievement DeserializeAchievement(JSONNode _buf)
    {
        return new Achievement(_buf);
    }

    /// <summary>
    /// 成就Id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 成就类型
    /// </summary>
    public readonly AchievementType AchievementType;
    /// <summary>
    /// 目标参数(按类型解释，通常取param[0])
    /// </summary>
    public readonly System.Collections.Generic.List<int> Param;
    /// <summary>
    /// 领取铜钱奖励
    /// </summary>
    public readonly int RewardCoin;
    /// <summary>
    /// 领取声望奖励
    /// </summary>
    public readonly int ReputationReward;
    /// <summary>
    /// 图标
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 成就品质等级
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 边框
    /// </summary>
    public readonly string Frame;
   
    public const int __ID__ = -879479025;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "achievementType:" + AchievementType + ","
        + "param:" + Luban.StringUtil.CollectionToString(Param) + ","
        + "rewardCoin:" + RewardCoin + ","
        + "reputationReward:" + ReputationReward + ","
        + "icon:" + Icon + ","
        + "level:" + Level + ","
        + "frame:" + Frame + ","
        + "}";
    }
}
}

