
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 酒楼设施
/// </summary>
public partial class TbFacility
{
    private readonly System.Collections.Generic.Dictionary<int, Facility> _dataMap;
    private readonly System.Collections.Generic.List<Facility> _dataList;
    
    public TbFacility(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, Facility>(count);
        _dataList = new System.Collections.Generic.List<Facility>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Facility _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.Facility.DeserializeFacility(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Facility> DataMap => _dataMap;
    public System.Collections.Generic.List<Facility> DataList => _dataList;

    public Facility GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Facility Get(int key) => _dataMap[key];
    public Facility this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

