
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 员工天赋
/// </summary>
public sealed partial class StaffTalent : Luban.BeanBase
{
    public StaffTalent(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["position"].IsNumber) { throw new SerializationException(); }  Position = (StaffPosition)_buf["position"].AsInt; }
        { if(!_buf["talentType"].IsNumber) { throw new SerializationException(); }  TalentType = (StaffTalentType)_buf["talentType"].AsInt; }
        { var __json0 = _buf["param"]; if(!__json0.IsArray) { throw new SerializationException(); } Param = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Param.Add(__v0); }   }
        { if(!_buf["sortOrder"].IsNumber) { throw new SerializationException(); }  SortOrder = _buf["sortOrder"]; }
        { if(!_buf["remark"].IsString) { throw new SerializationException(); }  Remark = _buf["remark"]; }
    }

    public static StaffTalent DeserializeStaffTalent(JSONNode _buf)
    {
        return new StaffTalent(_buf);
    }

    /// <summary>
    /// 天赋Id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 天赋名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 天赋描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 适用职位
    /// </summary>
    public readonly StaffPosition Position;
    /// <summary>
    /// 效果类型
    /// </summary>
    public readonly StaffTalentType TalentType;
    /// <summary>
    /// 效果参数
    /// </summary>
    public readonly System.Collections.Generic.List<int> Param;
    /// <summary>
    /// 排序
    /// </summary>
    public readonly int SortOrder;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Remark;
   
    public const int __ID__ = 833576908;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "position:" + Position + ","
        + "talentType:" + TalentType + ","
        + "param:" + Luban.StringUtil.CollectionToString(Param) + ","
        + "sortOrder:" + SortOrder + ","
        + "remark:" + Remark + ","
        + "}";
    }
}
}

