
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 对话台词行
/// </summary>
public sealed partial class Dialog : Luban.BeanBase
{
    public Dialog(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["dialogId"].IsString) { throw new SerializationException(); }  DialogId = _buf["dialogId"]; }
        { if(!_buf["order"].IsNumber) { throw new SerializationException(); }  Order = _buf["order"]; }
        { if(!_buf["headPic"].IsString) { throw new SerializationException(); }  HeadPic = _buf["headPic"]; }
        { if(!_buf["content"].IsString) { throw new SerializationException(); }  Content = _buf["content"]; }
    }

    public static Dialog DeserializeDialog(JSONNode _buf)
    {
        return new Dialog(_buf);
    }

    /// <summary>
    /// 行Id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 对话组Id
    /// </summary>
    public readonly string DialogId;
    /// <summary>
    /// 组内顺序
    /// </summary>
    public readonly int Order;
    /// <summary>
    /// 立绘键
    /// </summary>
    public readonly string HeadPic;
    /// <summary>
    /// 台词
    /// </summary>
    public readonly string Content;
   
    public const int __ID__ = 2046749032;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "dialogId:" + DialogId + ","
        + "order:" + Order + ","
        + "headPic:" + HeadPic + ","
        + "content:" + Content + ","
        + "}";
    }
}
}

