
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 员工属性
/// </summary>
public sealed partial class Staff : Luban.BeanBase
{
    public Staff(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["position"].IsNumber) { throw new SerializationException(); }  Position = (StaffPosition)_buf["position"].AsInt; }
        { if(!_buf["moveSpeed"].IsNumber) { throw new SerializationException(); }  MoveSpeed = _buf["moveSpeed"]; }
        { if(!_buf["staffTalent"].IsNumber) { throw new SerializationException(); }  StaffTalent = _buf["staffTalent"]; }
        { if(!_buf["recruitmentCosts"].IsNumber) { throw new SerializationException(); }  RecruitmentCosts = _buf["recruitmentCosts"]; }
        { if(!_buf["salary"].IsNumber) { throw new SerializationException(); }  Salary = _buf["salary"]; }
        { if(!_buf["visual"].IsString) { throw new SerializationException(); }  Visual = _buf["visual"]; }
        { if(!_buf["unlockLevel"].IsNumber) { throw new SerializationException(); }  UnlockLevel = _buf["unlockLevel"]; }
        { if(!_buf["remark"].IsString) { throw new SerializationException(); }  Remark = _buf["remark"]; }
    }

    public static Staff DeserializeStaff(JSONNode _buf)
    {
        return new Staff(_buf);
    }

    /// <summary>
    /// 员工Id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 姓名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 职位
    /// </summary>
    public readonly StaffPosition Position;
    /// <summary>
    /// 移动速度
    /// </summary>
    public readonly float MoveSpeed;
    /// <summary>
    /// 服务态度指数
    /// </summary>
    public readonly int StaffTalent;
    /// <summary>
    /// 招聘费用
    /// </summary>
    public readonly int RecruitmentCosts;
    /// <summary>
    /// 工资
    /// </summary>
    public readonly int Salary;
    /// <summary>
    /// 任务形象/预制体Key
    /// </summary>
    public readonly string Visual;
    /// <summary>
    /// 招聘槽解锁酒楼等级(0=不进固定槽)
    /// </summary>
    public readonly int UnlockLevel;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Remark;
   
    public const int __ID__ = 80204480;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "position:" + Position + ","
        + "moveSpeed:" + MoveSpeed + ","
        + "staffTalent:" + StaffTalent + ","
        + "recruitmentCosts:" + RecruitmentCosts + ","
        + "salary:" + Salary + ","
        + "visual:" + Visual + ","
        + "unlockLevel:" + UnlockLevel + ","
        + "remark:" + Remark + ","
        + "}";
    }
}
}

