
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 成就任务类型
    /// </summary>
    public enum AchievementType
    {
        /// <summary>
        /// 已实现：tavern.totalServedCustomers
        /// </summary>
        ServeCustomers = 1,
        /// <summary>
        /// 已实现：tavern.totalIncome（含柜台随机奖）
        /// </summary>
        EarnIncome = 2,
        /// <summary>
        /// 已实现：tavern.totalCookedDishes（偷菜不计）
        /// </summary>
        CookDishes = 3,
        /// <summary>
        /// 已实现：gameplay.businessOpenCount
        /// </summary>
        OpenBusiness = 4,
        /// <summary>
        /// ownedStaff 非临时在职数
        /// </summary>
        HireStaff = 5,
        /// <summary>
        /// 未实现：无晋升系统
        /// </summary>
        PromoteManager = 6,
        /// <summary>
        /// achievementStats.unlockedStaffTalentIds（接口预留）
        /// </summary>
        CollectTalent = 7,
        /// <summary>
        /// GetUnlockedTableCount()
        /// </summary>
        ExpandTavern = 8,
        /// <summary>
        /// achievementStats.totalVipCheckout
        /// </summary>
        ServeVip = 10,
        /// <summary>
        /// achievementStats.totalVipSuccessfulServe
        /// </summary>
        ServeVipSuccess = 11,
        /// <summary>
        /// achievementStats.peakVipSingleTableIncome
        /// </summary>
        VipSingleSpendReached = 12,
        /// <summary>
        /// achievementStats.peakVipConcurrentCount
        /// </summary>
        VipConcurrentCount = 13,
        /// <summary>
        /// achievementStats.totalVipNegativeWalkout
        /// </summary>
        VipWalkout = 14,
        /// <summary>
        /// 四段等待均 &lt; 5s
        /// </summary>
        PerfectBusinessDay = 15,
        /// <summary>
        /// achievementStats.peakSessionServedCustomers
        /// </summary>
        ServeCustomersOneDay = 16,
        /// <summary>
        /// 未实现：param[0]=满意度阈值 param[1]=人数
        /// </summary>
        SaveImpatientCustomer = 17,
        /// <summary>
        /// achievementStats.peakQueueLength
        /// </summary>
        QueueLengthReached = 18,
        /// <summary>
        /// achievementStats.peakPendingServeDishes
        /// </summary>
        PendingServeDishes = 19,
        /// <summary>
        /// achievementStats.peakPendingCheckoutTables
        /// </summary>
        PendingCheckoutTables = 20,
        /// <summary>
        /// achievementStats.peakDirtyTables
        /// </summary>
        DirtyTablePeak = 21,
        /// <summary>
        /// achievementStats.totalSlowServeWalkout
        /// </summary>
        SlowServeWalkout = 22,
        /// <summary>
        /// achievementStats.totalLongWaitWalkout
        /// </summary>
        LongWaitWalkout = 23,
        /// <summary>
        /// achievementStats.totalManualServiceActions
        /// </summary>
        ManualServiceActions = 24,
        /// <summary>
        /// achievementStats.autoServiceDayCount
        /// </summary>
        AutoServiceDay = 25,
        /// <summary>
        /// 未实现：无价格敏感离场统计
        /// </summary>
        HighPriceWalkout = 26,
        /// <summary>
        /// achievementStats.negativeProfitDayCount
        /// </summary>
        NegativeProfitDay = 27,
        /// <summary>
        /// 可部分实现：统计已达成未领+已领
        /// </summary>
        CompleteAchievements = 28,
        /// <summary>
        /// 购买家具数量
        /// </summary>
        BuyFacility = 29,
        /// <summary>
        /// 雇佣伙计
        /// </summary>
        EmployFellow = 30,
        /// <summary>
        /// 酒楼升级
        /// </summary>
        UpgradeLevel = 31,
        /// <summary>
        /// 收钱 n 桌
        /// </summary>
        TakeMoney = 32,
        /// <summary>
        /// 踢偷懒店小二 n 次
        /// </summary>
        KickEmployee = 33,
        /// <summary>
        /// 成功拉客n次
        /// </summary>
        Solicit = 34,
        /// <summary>
        /// 扩建
        /// </summary>
        Expand = 35,
        /// <summary>
        /// 楼梯
        /// </summary>
        Stairs = 36,
    }

} 

