
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Config : Luban.BeanBase
{
    public Config(JSONNode _buf) 
    {
        { if(!_buf["configName"].IsString) { throw new SerializationException(); }  ConfigName = _buf["configName"]; }
        { var __json0 = _buf["value"]; if(!__json0.IsArray) { throw new SerializationException(); } Value = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Value.Add(__v0); }   }
    }

    public static Config DeserializeConfig(JSONNode _buf)
    {
        return new Config(_buf);
    }

    /// <summary>
    /// 配置名称
    /// </summary>
    public readonly string ConfigName;
    /// <summary>
    /// 数值
    /// </summary>
    public readonly System.Collections.Generic.List<int> Value;
   
    public const int __ID__ = 2024042338;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "configName:" + ConfigName + ","
        + "value:" + Luban.StringUtil.CollectionToString(Value) + ","
        + "}";
    }
}
}

