
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 员工科技原子效果
    /// </summary>
    public enum StaffTechEffect
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 会点单
        /// </summary>
        GrantCanOrder = 1,
        /// <summary>
        /// 会上菜
        /// </summary>
        GrantCanServe = 2,
        /// <summary>
        /// 会收账
        /// </summary>
        GrantCanCheckout = 3,
        /// <summary>
        /// 移速
        /// </summary>
        ImproveMoveSpeed = 4,
        /// <summary>
        /// 点单耗时
        /// </summary>
        ImproveOrderTime = 5,
        /// <summary>
        /// 上菜耗时
        /// </summary>
        ImproveServeTime = 6,
        /// <summary>
        /// 收账耗时
        /// </summary>
        ImproveCheckoutTime = 7,
        /// <summary>
        /// 清扫耗时
        /// </summary>
        ImproveCleanTime = 8,
        /// <summary>
        /// 做菜速度
        /// </summary>
        ImproveCookSpeed = 9,
        /// <summary>
        /// 柜台随机金币
        /// </summary>
        EnableCounterRandomReward = 10,
    }

} 

