
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 员工职位
    /// </summary>
    public enum StaffPosition
    {
        /// <summary>
        /// 掌柜
        /// </summary>
        Shopkeeper = 1,
        /// <summary>
        /// 厨师
        /// </summary>
        Chef = 2,
        /// <summary>
        /// 小二
        /// </summary>
        Waiter = 3,
    }

} 

