
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 员工天赋效果类型
    /// </summary>
    public enum StaffTalentType
    {
        /// <summary>
        /// 无效果
        /// </summary>
        NoEffect = 0,
        /// <summary>
        /// 移速加成
        /// </summary>
        MoveSpeedBonusPercent = 1,
        /// <summary>
        /// 点单加速
        /// </summary>
        OrderSpeedBonusPercent = 2,
        /// <summary>
        /// 上菜加速
        /// </summary>
        ServeSpeedBonusPercent = 3,
        /// <summary>
        /// 收账加速
        /// </summary>
        CheckoutSpeedBonusPercent = 4,
        /// <summary>
        /// 清扫加速
        /// </summary>
        CleanSpeedBonusPercent = 5,
        /// <summary>
        /// 全服务加速
        /// </summary>
        AllServiceSpeedBonusPercent = 6,
        /// <summary>
        /// 体力消耗降低
        /// </summary>
        StaminaDrainReductionPercent = 7,
        /// <summary>
        /// 顾客耐心
        /// </summary>
        CustomerPatienceBonusSeconds = 8,
        /// <summary>
        /// 小费概率
        /// </summary>
        TipChanceBonusPercent = 9,
        /// <summary>
        /// 揽客加速
        /// </summary>
        SolicitationSpeedBonusPercent = 10,
        /// <summary>
        /// 满意度加成
        /// </summary>
        SatisfactionBonusPercent = 11,
        /// <summary>
        /// 贵客服务加速
        /// </summary>
        VipServiceSpeedBonusPercent = 12,
        /// <summary>
        /// 高价菜概率
        /// </summary>
        HighPriceDishChanceBonusPercent = 13,
        /// <summary>
        /// 酒水销售概率
        /// </summary>
        WineSaleChanceBonusPercent = 14,
        /// <summary>
        /// 端菜容量
        /// </summary>
        CarryDishCapacitySet = 15,
        /// <summary>
        /// 批量点单
        /// </summary>
        OrderBatchCountSet = 16,
        /// <summary>
        /// 上菜后顺路清扫
        /// </summary>
        AutoCleanNearbyAfterServe = 17,
        /// <summary>
        /// 自动支援
        /// </summary>
        AutoSupportMostBackloggedTask = 18,
        /// <summary>
        /// 优先久等顾客
        /// </summary>
        PrioritizeLongestWaitingCustomer = 19,
        /// <summary>
        /// 优先低耐心顾客
        /// </summary>
        PrioritizeLowPatienceCustomer = 20,
        /// <summary>
        /// 高客座效率
        /// </summary>
        OccupancyEfficiencyBonus = 21,
        /// <summary>
        /// 结账后清扫
        /// </summary>
        AutoCleanAfterCheckout = 22,
        /// <summary>
        /// 动作后摇降低
        /// </summary>
        WaiterPostActionDelayReductionPercent = 23,
        /// <summary>
        /// 管理
        /// </summary>
        Management = 24,
        /// <summary>
        /// 全员小二全服务加速
        /// </summary>
        WaiterAllServiceSpeedBonusPercent = 25,
        /// <summary>
        /// 全员厨师烹饪加速
        /// </summary>
        ChefAllCookingSpeedBonusPercent = 26,
        /// <summary>
        /// 团队高客座效率
        /// </summary>
        TeamOccupancyEfficiencyBonus = 27,
        /// <summary>
        /// 团队清扫加速
        /// </summary>
        TeamCleanSpeedBonusPercent = 28,
        /// <summary>
        /// 团队上菜加速
        /// </summary>
        TeamServeSpeedBonusPercent = 29,
        /// <summary>
        /// 团队收账加速
        /// </summary>
        TeamCheckoutSpeedBonusPercent = 30,
        /// <summary>
        /// 团队点单加速
        /// </summary>
        TeamOrderSpeedBonusPercent = 31,
        /// <summary>
        /// 招聘费用降低
        /// </summary>
        RecruitmentCostReductionPercent = 32,
        /// <summary>
        /// 日薪支出降低
        /// </summary>
        DailyWageReductionPercent = 33,
        /// <summary>
        /// 贵客吸引力
        /// </summary>
        VipAttractionBonusPercent = 34,
        /// <summary>
        /// 全店工作效率
        /// </summary>
        TavernAllWorkSpeedBonusPercent = 35,
        /// <summary>
        /// 厨师备菜加速
        /// </summary>
        ChefPrepSpeedBonusPercent = 36,
        /// <summary>
        /// 额外出菜概率
        /// </summary>
        ExtraDishChancePercent = 37,
        /// <summary>
        /// 食材消耗降低
        /// </summary>
        IngredientCostReductionPercent = 38,
    }

} 

