
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    /// <summary>
    /// 全局KV配置
    /// </summary>
    public TbConfig TbConfig {get; }
    /// <summary>
    /// 引导任务/小目标
    /// </summary>
    public TbGuideTask TbGuideTask {get; }
    /// <summary>
    /// 员工属性
    /// </summary>
    public TbStaff TbStaff {get; }
    /// <summary>
    /// 酒楼设施
    /// </summary>
    public TbFacility TbFacility {get; }
    /// <summary>
    /// 酒馆科技树
    /// </summary>
    public TbTavernTech TbTavernTech {get; }
    /// <summary>
    /// 经营成就任务
    /// </summary>
    public TbAchievement TbAchievement {get; }
    /// <summary>
    /// 菜品配置
    /// </summary>
    public TbDish TbDish {get; }
    /// <summary>
    /// 贵客猜菜提示语
    /// </summary>
    public TbVipGuestDemandHint TbVipGuestDemandHint {get; }
    /// <summary>
    /// 员工天赋
    /// </summary>
    public TbStaffTalent TbStaffTalent {get; }
    /// <summary>
    /// 城镇他人建筑
    /// </summary>
    public TbTownBuilding TbTownBuilding {get; }
    /// <summary>
    /// 对话台词
    /// </summary>
    public TbDialog TbDialog {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbConfig = new TbConfig(loader("tbconfig"));
        TbGuideTask = new TbGuideTask(loader("tbguidetask"));
        TbStaff = new TbStaff(loader("tbstaff"));
        TbFacility = new TbFacility(loader("tbfacility"));
        TbTavernTech = new TbTavernTech(loader("tbtaverntech"));
        TbAchievement = new TbAchievement(loader("tbachievement"));
        TbDish = new TbDish(loader("tbdish"));
        TbVipGuestDemandHint = new TbVipGuestDemandHint(loader("tbvipguestdemandhint"));
        TbStaffTalent = new TbStaffTalent(loader("tbstafftalent"));
        TbTownBuilding = new TbTownBuilding(loader("tbtownbuilding"));
        TbDialog = new TbDialog(loader("tbdialog"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbConfig.ResolveRef(this);
        TbGuideTask.ResolveRef(this);
        TbStaff.ResolveRef(this);
        TbFacility.ResolveRef(this);
        TbTavernTech.ResolveRef(this);
        TbAchievement.ResolveRef(this);
        TbDish.ResolveRef(this);
        TbVipGuestDemandHint.ResolveRef(this);
        TbStaffTalent.ResolveRef(this);
        TbTownBuilding.ResolveRef(this);
        TbDialog.ResolveRef(this);
    }
}

}
