
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 酒馆科技树
/// </summary>
public sealed partial class TavernTech : Luban.BeanBase
{
    public TavernTech(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["techType"].IsNumber) { throw new SerializationException(); }  TechType = (TavernTechType)_buf["techType"].AsInt; }
        { var __json0 = _buf["param"]; if(!__json0.IsArray) { throw new SerializationException(); } Param = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Param.Add(__v0); }   }
        { var __json0 = _buf["unlock"]; if(!__json0.IsArray) { throw new SerializationException(); } Unlock = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Unlock.Add(__v0); }   }
        { if(!_buf["cost"].IsNumber) { throw new SerializationException(); }  Cost = _buf["cost"]; }
        { if(!_buf["researchTime"].IsNumber) { throw new SerializationException(); }  ResearchTime = _buf["researchTime"]; }
        { if(!_buf["sortOrder"].IsNumber) { throw new SerializationException(); }  SortOrder = _buf["sortOrder"]; }
        { if(!_buf["remark"].IsString) { throw new SerializationException(); }  Remark = _buf["remark"]; }
        { var _j = _buf["staffPosition"]; if (_j.Tag != JSONNodeType.None && _j.Tag != JSONNodeType.NullValue) { { if(!_j.IsNumber) { throw new SerializationException(); }  StaffPosition = (StaffPosition?)_j.AsInt; } } else { StaffPosition = null; } }
        { if(!_buf["staffEffect"].IsNumber) { throw new SerializationException(); }  StaffEffect = (StaffTechEffect)_buf["staffEffect"].AsInt; }
        { if(!_buf["effName"].IsString) { throw new SerializationException(); }  EffName = _buf["effName"]; }
        { if(!_buf["icon"].IsString) { throw new SerializationException(); }  Icon = _buf["icon"]; }
        { if(!_buf["staffEffectValue"].IsNumber) { throw new SerializationException(); }  StaffEffectValue = _buf["staffEffectValue"]; }
    }

    public static TavernTech DeserializeTavernTech(JSONNode _buf)
    {
        return new TavernTech(_buf);
    }

    /// <summary>
    /// 科技Id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 科技名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 效果类型
    /// </summary>
    public readonly TavernTechType TechType;
    /// <summary>
    /// 效果参数(按techType解释)
    /// </summary>
    public readonly System.Collections.Generic.List<int> Param;
    /// <summary>
    /// 前置科技Id列表
    /// </summary>
    public readonly System.Collections.Generic.List<int> Unlock;
    /// <summary>
    /// 研究花费
    /// </summary>
    public readonly int Cost;
    /// <summary>
    /// 研究需招待顾客(结算)数量
    /// </summary>
    public readonly int ResearchTime;
    /// <summary>
    /// 排序
    /// </summary>
    public readonly int SortOrder;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Remark;
    /// <summary>
    /// 员工职位(非员工科技留空)
    /// </summary>
    public readonly StaffPosition? StaffPosition;
    /// <summary>
    /// 员工原子效果
    /// </summary>
    public readonly StaffTechEffect StaffEffect;
    /// <summary>
    /// 特效预制体
    /// </summary>
    public readonly string EffName;
    /// <summary>
    /// 科技icon
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 效果值(千分比/开关0-1)
    /// </summary>
    public readonly int StaffEffectValue;
   
    public const int __ID__ = -546995218;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "techType:" + TechType + ","
        + "param:" + Luban.StringUtil.CollectionToString(Param) + ","
        + "unlock:" + Luban.StringUtil.CollectionToString(Unlock) + ","
        + "cost:" + Cost + ","
        + "researchTime:" + ResearchTime + ","
        + "sortOrder:" + SortOrder + ","
        + "remark:" + Remark + ","
        + "staffPosition:" + StaffPosition + ","
        + "staffEffect:" + StaffEffect + ","
        + "effName:" + EffName + ","
        + "icon:" + Icon + ","
        + "staffEffectValue:" + StaffEffectValue + ","
        + "}";
    }
}
}

