
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 经营成就任务
/// </summary>
public partial class TbAchievement
{
    private readonly System.Collections.Generic.Dictionary<int, Achievement> _dataMap;
    private readonly System.Collections.Generic.List<Achievement> _dataList;
    
    public TbAchievement(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, Achievement>(count);
        _dataList = new System.Collections.Generic.List<Achievement>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Achievement _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.Achievement.DeserializeAchievement(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Achievement> DataMap => _dataMap;
    public System.Collections.Generic.List<Achievement> DataList => _dataList;

    public Achievement GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Achievement Get(int key) => _dataMap[key];
    public Achievement this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

