
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 全局KV配置
/// </summary>
public partial class TbConfig
{
    private readonly System.Collections.Generic.List<Config> _dataList;


    public TbConfig(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataList = new System.Collections.Generic.List<Config>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Config _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.Config.DeserializeConfig(_ele);  }
            _dataList.Add(_v);
        }
    }

    public System.Collections.Generic.List<Config> DataList => _dataList;

    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}

