
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 菜品配置
/// </summary>
public partial class TbDish
{
    private readonly System.Collections.Generic.Dictionary<int, Dish> _dataMap;
    private readonly System.Collections.Generic.List<Dish> _dataList;
    
    public TbDish(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, Dish>(count);
        _dataList = new System.Collections.Generic.List<Dish>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Dish _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.Dish.DeserializeDish(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Dish> DataMap => _dataMap;
    public System.Collections.Generic.List<Dish> DataList => _dataList;

    public Dish GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Dish Get(int key) => _dataMap[key];
    public Dish this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

