
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 对话台词
/// </summary>
public partial class TbDialog
{
    private readonly System.Collections.Generic.Dictionary<int, Dialog> _dataMap;
    private readonly System.Collections.Generic.List<Dialog> _dataList;
    
    public TbDialog(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, Dialog>(count);
        _dataList = new System.Collections.Generic.List<Dialog>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Dialog _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.Dialog.DeserializeDialog(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Dialog> DataMap => _dataMap;
    public System.Collections.Generic.List<Dialog> DataList => _dataList;

    public Dialog GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Dialog Get(int key) => _dataMap[key];
    public Dialog this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

