
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 引导任务/小目标
/// </summary>
public partial class TbGuideTask
{
    private readonly System.Collections.Generic.Dictionary<int, GuideTask> _dataMap;
    private readonly System.Collections.Generic.List<GuideTask> _dataList;
    
    public TbGuideTask(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, GuideTask>(count);
        _dataList = new System.Collections.Generic.List<GuideTask>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            GuideTask _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.GuideTask.DeserializeGuideTask(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, GuideTask> DataMap => _dataMap;
    public System.Collections.Generic.List<GuideTask> DataList => _dataList;

    public GuideTask GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public GuideTask Get(int key) => _dataMap[key];
    public GuideTask this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

