
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 员工属性
/// </summary>
public partial class TbStaff
{
    private readonly System.Collections.Generic.Dictionary<int, Staff> _dataMap;
    private readonly System.Collections.Generic.List<Staff> _dataList;
    
    public TbStaff(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, Staff>(count);
        _dataList = new System.Collections.Generic.List<Staff>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Staff _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.Staff.DeserializeStaff(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Staff> DataMap => _dataMap;
    public System.Collections.Generic.List<Staff> DataList => _dataList;

    public Staff GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Staff Get(int key) => _dataMap[key];
    public Staff this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

