
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 员工天赋
/// </summary>
public partial class TbStaffTalent
{
    private readonly System.Collections.Generic.Dictionary<int, StaffTalent> _dataMap;
    private readonly System.Collections.Generic.List<StaffTalent> _dataList;
    
    public TbStaffTalent(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, StaffTalent>(count);
        _dataList = new System.Collections.Generic.List<StaffTalent>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            StaffTalent _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.StaffTalent.DeserializeStaffTalent(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, StaffTalent> DataMap => _dataMap;
    public System.Collections.Generic.List<StaffTalent> DataList => _dataList;

    public StaffTalent GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public StaffTalent Get(int key) => _dataMap[key];
    public StaffTalent this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

