
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 酒馆科技树
/// </summary>
public partial class TbTavernTech
{
    private readonly System.Collections.Generic.Dictionary<int, TavernTech> _dataMap;
    private readonly System.Collections.Generic.List<TavernTech> _dataList;
    
    public TbTavernTech(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, TavernTech>(count);
        _dataList = new System.Collections.Generic.List<TavernTech>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            TavernTech _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.TavernTech.DeserializeTavernTech(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, TavernTech> DataMap => _dataMap;
    public System.Collections.Generic.List<TavernTech> DataList => _dataList;

    public TavernTech GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public TavernTech Get(int key) => _dataMap[key];
    public TavernTech this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

