
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 城镇他人建筑
/// </summary>
public partial class TbTownBuilding
{
    private readonly System.Collections.Generic.Dictionary<int, TownBuilding> _dataMap;
    private readonly System.Collections.Generic.List<TownBuilding> _dataList;
    
    public TbTownBuilding(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, TownBuilding>(count);
        _dataList = new System.Collections.Generic.List<TownBuilding>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            TownBuilding _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.TownBuilding.DeserializeTownBuilding(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, TownBuilding> DataMap => _dataMap;
    public System.Collections.Generic.List<TownBuilding> DataList => _dataList;

    public TownBuilding GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public TownBuilding Get(int key) => _dataMap[key];
    public TownBuilding this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

