
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 城镇他人建筑
/// </summary>
public sealed partial class TownBuilding : Luban.BeanBase
{
    public TownBuilding(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["playerId"].IsNumber) { throw new SerializationException(); }  PlayerId = _buf["playerId"]; }
        { if(!_buf["fieldId"].IsNumber) { throw new SerializationException(); }  FieldId = _buf["fieldId"]; }
        { if(!_buf["buildingLevel"].IsNumber) { throw new SerializationException(); }  BuildingLevel = _buf["buildingLevel"]; }
        { if(!_buf["hotMark"].IsNumber) { throw new SerializationException(); }  HotMark = _buf["hotMark"]; }
        { if(!_buf["headIconId"].IsNumber) { throw new SerializationException(); }  HeadIconId = _buf["headIconId"]; }
    }

    public static TownBuilding DeserializeTownBuilding(JSONNode _buf)
    {
        return new TownBuilding(_buf);
    }

    /// <summary>
    /// 主键
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 店主名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 虚拟玩家Id
    /// </summary>
    public readonly int PlayerId;
    /// <summary>
    /// 地块Id(Tile_1~8)
    /// </summary>
    public readonly int FieldId;
    /// <summary>
    /// 建筑等级
    /// </summary>
    public readonly int BuildingLevel;
    /// <summary>
    /// 火爆标记
    /// </summary>
    public readonly int HotMark;
    /// <summary>
    /// 玩家头像Id
    /// </summary>
    public readonly int HeadIconId;
   
    public const int __ID__ = 127107974;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "playerId:" + PlayerId + ","
        + "fieldId:" + FieldId + ","
        + "buildingLevel:" + BuildingLevel + ","
        + "hotMark:" + HotMark + ","
        + "headIconId:" + HeadIconId + ","
        + "}";
    }
}
}

