
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 引导小目标任务
/// </summary>
public sealed partial class GuideTask : Luban.BeanBase
{
    public GuideTask(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["taskType"].IsNumber) { throw new SerializationException(); }  TaskType = (GuideTaskType)_buf["taskType"].AsInt; }
        { var __json0 = _buf["param"]; if(!__json0.IsArray) { throw new SerializationException(); } Param = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Param.Add(__v0); }   }
        { var __json0 = _buf["unlock"]; if(!__json0.IsArray) { throw new SerializationException(); } Unlock = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Unlock.Add(__v0); }   }
    }

    public static GuideTask DeserializeGuideTask(JSONNode _buf)
    {
        return new GuideTask(_buf);
    }

    /// <summary>
    /// 任务Id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 描述文字
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 任务类型
    /// </summary>
    public readonly GuideTaskType TaskType;
    /// <summary>
    /// 关联参数列表(按taskType解释)
    /// </summary>
    public readonly System.Collections.Generic.List<int> Param;
    /// <summary>
    /// 解锁前置任务Id列表
    /// </summary>
    public readonly System.Collections.Generic.List<int> Unlock;
   
    public const int __ID__ = -72472959;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "desc:" + Desc + ","
        + "taskType:" + TaskType + ","
        + "param:" + Luban.StringUtil.CollectionToString(Param) + ","
        + "unlock:" + Luban.StringUtil.CollectionToString(Unlock) + ","
        + "}";
    }
}
}

