
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 酒馆科技效果类型
    /// </summary>
    public enum TavernTechType
    {
        /// <summary>
        /// 增加小二上限
        /// </summary>
        ExtraWaiterCap = 1,
        /// <summary>
        /// 增加厨师上限
        /// </summary>
        ExtraChefCap = 2,
        /// <summary>
        /// 增加掌柜上限
        /// </summary>
        ExtraShopkeeperCap = 3,
        /// <summary>
        /// 增加排队容量
        /// </summary>
        QueueCap = 4,
        /// <summary>
        /// 营业时长加成秒
        /// </summary>
        BusinessHoursBonus = 5,
        /// <summary>
        /// 刷客间隔千分比
        /// </summary>
        CustomerRefreshMul = 6,
        /// <summary>
        /// 涨价利润额外百分比
        /// </summary>
        PriceProfitBonus = 7,
        /// <summary>
        /// 鼓舞客流额外百分比
        /// </summary>
        InspireBonus = 8,
        /// <summary>
        /// 研究耗时千分比
        /// </summary>
        ResearchSpeedMul = 9,
        /// <summary>
        /// 全店小费百分比
        /// </summary>
        TipGlobalBonus = 10,
        /// <summary>
        /// 解锁员工等级
        /// </summary>
        UnlockStaffLevel = 11,
        /// <summary>
        /// param 为减去的秒数
        /// </summary>
        CustomerRefreshSecondsBonus = 12,
        /// <summary>
        /// 营业时长千分比倍率
        /// </summary>
        BusinessHoursMul = 13,
        /// <summary>
        /// 解锁小二行为自动升级
        /// </summary>
        EnableWaiterAutoUpgrade = 14,
        /// <summary>
        /// 解锁厨师做菜自动升级
        /// </summary>
        EnableChefAutoUpgrade = 15,
        /// <summary>
        /// 解锁贵客玩法
        /// </summary>
        EnableVipCustomer = 16,
        /// <summary>
        /// 解锁拉客玩法
        /// </summary>
        EnableVisitCustomer = 17,
        /// <summary>
        /// 自定义
        /// </summary>
        Custom = 99,
    }

} 

