
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 设施类型
    /// </summary>
    public enum FacilityType
    {
        /// <summary>
        /// 桌子
        /// </summary>
        Table = 1,
        /// <summary>
        /// 掌柜桌
        /// </summary>
        Counter = 2,
        /// <summary>
        /// 灶台
        /// </summary>
        Stove = 3,
        /// <summary>
        /// 炉子
        /// </summary>
        Furnace = 4,
        /// <summary>
        /// 酒柜
        /// </summary>
        WineCabinet = 5,
        /// <summary>
        /// 柜子
        /// </summary>
        Cabinet = 6,
        /// <summary>
        /// 厨房桌
        /// </summary>
        KitchenTable = 7,
        /// <summary>
        /// 轿子
        /// </summary>
        Jiaozi = 8,
        /// <summary>
        /// 楼梯
        /// </summary>
        Stairs = 9,
        /// <summary>
        /// 戏台
        /// </summary>
        Stage = 10,
        /// <summary>
        /// 二楼桌子
        /// </summary>
        SecondFloorTable = 11,
        /// <summary>
        /// 二楼装饰
        /// </summary>
        Decoration = 12,
    }

} 

