
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 引导任务类型
    /// </summary>
    public enum GuideTaskType
    {
        /// <summary>
        /// 购买基础设施
        /// </summary>
        BuyBasicEquipment = 1,
        /// <summary>
        /// 购买桌子
        /// </summary>
        BuyTables = 2,
        /// <summary>
        /// 购买厨房设施
        /// </summary>
        BuyKitchenEquipment = 3,
        /// <summary>
        /// 招聘掌柜
        /// </summary>
        HireShopkeeper = 4,
        /// <summary>
        /// 招聘厨师
        /// </summary>
        HireChef = 5,
        /// <summary>
        /// 招聘小二
        /// </summary>
        HireWaiter = 6,
        /// <summary>
        /// 自定义
        /// </summary>
        Custom = 99,
    }

} 

