
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 酒楼设施
/// </summary>
public sealed partial class Facility : Luban.BeanBase
{
    public Facility(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["facilityType"].IsNumber) { throw new SerializationException(); }  FacilityType = (FacilityType)_buf["facilityType"].AsInt; }
        { if(!_buf["bindNode"].IsString) { throw new SerializationException(); }  BindNode = _buf["bindNode"]; }
        { if(!_buf["guideKey"].IsString) { throw new SerializationException(); }  GuideKey = _buf["guideKey"]; }
        { if(!_buf["equipmentId"].IsNumber) { throw new SerializationException(); }  EquipmentId = _buf["equipmentId"]; }
        { var __json0 = _buf["unlock"]; if(!__json0.IsArray) { throw new SerializationException(); } Unlock = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Unlock.Add(__v0); }   }
        { if(!_buf["unlockIncome"].IsNumber) { throw new SerializationException(); }  UnlockIncome = _buf["unlockIncome"]; }
        { if(!_buf["cost"].IsNumber) { throw new SerializationException(); }  Cost = _buf["cost"]; }
        { var __json0 = _buf["upgradeGroup"]; if(!__json0.IsArray) { throw new SerializationException(); } UpgradeGroup = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  UpgradeGroup.Add(__v0); }   }
        { if(!_buf["sortOrder"].IsNumber) { throw new SerializationException(); }  SortOrder = _buf["sortOrder"]; }
        { if(!_buf["unlockLevel"].IsNumber) { throw new SerializationException(); }  UnlockLevel = _buf["unlockLevel"]; }
        { if(!_buf["getPresitige"].IsNumber) { throw new SerializationException(); }  GetPresitige = _buf["getPresitige"]; }
        { if(!_buf["remark"].IsString) { throw new SerializationException(); }  Remark = _buf["remark"]; }
    }

    public static Facility DeserializeFacility(JSONNode _buf)
    {
        return new Facility(_buf);
    }

    /// <summary>
    /// 设施Id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 显示名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 设施类型
    /// </summary>
    public readonly FacilityType FacilityType;
    /// <summary>
    /// 场景绑定节点名
    /// </summary>
    public readonly string BindNode;
    /// <summary>
    /// 引导逻辑Key
    /// </summary>
    public readonly string GuideKey;
    /// <summary>
    /// 关联SO_EquipmentId(无则0)
    /// </summary>
    public readonly int EquipmentId;
    /// <summary>
    /// 解锁前置设施Id列表
    /// </summary>
    public readonly System.Collections.Generic.List<int> Unlock;
    /// <summary>
    /// 解锁所需累计营收(0忽略)
    /// </summary>
    public readonly int UnlockIncome;
    /// <summary>
    /// 解锁花费
    /// </summary>
    public readonly int Cost;
    /// <summary>
    /// 升级用设备Id组(SO_Equipment)
    /// </summary>
    public readonly System.Collections.Generic.List<int> UpgradeGroup;
    /// <summary>
    /// 同类型排序
    /// </summary>
    public readonly int SortOrder;
    /// <summary>
    /// 所需酒楼等级
    /// </summary>
    public readonly int UnlockLevel;
    /// <summary>
    /// 获得声望
    /// </summary>
    public readonly int GetPresitige;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Remark;
   
    public const int __ID__ = 565760707;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "facilityType:" + FacilityType + ","
        + "bindNode:" + BindNode + ","
        + "guideKey:" + GuideKey + ","
        + "equipmentId:" + EquipmentId + ","
        + "unlock:" + Luban.StringUtil.CollectionToString(Unlock) + ","
        + "unlockIncome:" + UnlockIncome + ","
        + "cost:" + Cost + ","
        + "upgradeGroup:" + Luban.StringUtil.CollectionToString(UpgradeGroup) + ","
        + "sortOrder:" + SortOrder + ","
        + "unlockLevel:" + UnlockLevel + ","
        + "getPresitige:" + GetPresitige + ","
        + "remark:" + Remark + ","
        + "}";
    }
}
}

