
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 菜品配置
/// </summary>
public sealed partial class Dish : Luban.BeanBase
{
    public Dish(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { var __json0 = _buf["materials"]; if(!__json0.IsArray) { throw new SerializationException(); } Materials = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  Materials.Add(__v0); }   }
        { var __json0 = _buf["flavor"]; if(!__json0.IsArray) { throw new SerializationException(); } Flavor = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  Flavor.Add(__v0); }   }
        { if(!_buf["icon"].IsString) { throw new SerializationException(); }  Icon = _buf["icon"]; }
        { if(!_buf["summary"].IsString) { throw new SerializationException(); }  Summary = _buf["summary"]; }
        { if(!_buf["price"].IsNumber) { throw new SerializationException(); }  Price = _buf["price"]; }
    }

    public static Dish DeserializeDish(JSONNode _buf)
    {
        return new Dish(_buf);
    }

    /// <summary>
    /// 菜品Id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 菜名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 材料标签
    /// </summary>
    public readonly System.Collections.Generic.List<string> Materials;
    /// <summary>
    /// 口味标签
    /// </summary>
    public readonly System.Collections.Generic.List<string> Flavor;
    /// <summary>
    /// 图标Resources路径
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 简单描述
    /// </summary>
    public readonly string Summary;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly int Price;
   
    public const int __ID__ = 2130362;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "materials:" + Luban.StringUtil.CollectionToString(Materials) + ","
        + "flavor:" + Luban.StringUtil.CollectionToString(Flavor) + ","
        + "icon:" + Icon + ","
        + "summary:" + Summary + ","
        + "price:" + Price + ","
        + "}";
    }
}
}

